### ISSUE TITLE
Cancel hearbeat on Close connection

### ISSUE THREAD

**Issue by VitalySh** [Polyconseil/aioamqp#114] opened 2016-10-06 04:44 UTC
The time between events depends sraight on hearbeat value

2016-10-06 11:35:55,628 | INFO    | 14179 | aioamqp.protocol    | 286 | Close connection
2016-10-06 11:36:10,999 | WARNING | 14179 | aioamqp.protocol    | 100 | Connection lost exc=None

**Comment by RemiCardona** [comment] 2016-10-06 11:07
Are you using 0.8.2 ? Can you share a test case to reproduce the issue ?

Thanks

**Comment by vi-sh** [comment] 2016-10-07 01:48
pip  show aioamqp
---
Metadata-Version: 2.0
Name: aioamqp
Version: 0.8.2
Summary: AMQP implementation using asyncio
Home-page: https://github.com/polyconseil/aioamqp
Author: Polyconseil dev' team
Author-email: opensource+aioamqp@polyconseil.fr
Installer: pip
License: BSD
Location: /home/vish/aio-transmute/lib/python3.5/site-packages
Requires: 
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  License :: OSI Approved :: BSD License
  Operating System :: OS Independent
  Programming Language :: Python
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.3
  Programming Language :: Python :: 3.4

Steps to reproduce
---
1. Set heartbeat to any significant values
2. Stop or restart RabbitMQ server

**Comment by RemiCardona** [comment] 2016-10-21 11:35
The steps you mention is how I tested the heartbeat code in 0.8.2 and I can't reproduce.

You'll have to show me how the issue behaves with your code. Turn on DEBUG level logging on the `aioamqp` logger, add prints wherever necessary, etc.

Thanks

**Comment by RemiCardona** [comment] 2017-03-23 13:52
Can't reproduce. Closing.

**Closed by RemiCardona** 2017-03-23 13:52 UTC
